apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networks.samplecrd.k8s.io
  annotations:
    api-approved.kubernetes.io: "unapproved: https://example.com/your-reason"
spec:
  group: samplecrd.k8s.io
  names:
    kind: Network
    plural: networks
    singular: network
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cidr:
                  type: string
                gateway:
                  type: string